baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Apps Tea | Apps & Games "
[[menu.main]]
URL = "/portfolio"
name = "Portfolio"
weight = "2"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = "Minsk, Belarus"
author = "Tea Drinker"
copyright = "Copyrighht &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "This is meta description"
email = "i@appstea.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "images/appstea.png"
phone = "+375 29 Xx Xx Xxx"
theme_color = "#57969b"
[params.contact]
enable = true
form_action = "mailto:general.appsetea@gmail.com"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.facebook.com/Apps-Tea-104663531235412/"
icon = "ti-facebook"
[[params.social]]
URL = "https://twitter.com/AppsTea"
icon = "ti-twitter-alt"
